# Generated by Django 4.2.2 on 2023-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('P', 'Private Limited Company'), ('S', 'Self-Employed Person'), ('N', 'Nonprofit Association'), ('O', 'Other')], max_length=1)),
                ('role', models.CharField(choices=[('P', 'Provider'), ('C', 'Customer')], max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('registry_code', models.CharField(max_length=20)),
                ('vat_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT number')),
                ('iban', models.CharField(max_length=40, verbose_name='IBAN')),
                ('bic_swift', models.CharField(max_length=15, verbose_name='BIC/SWIFT')),
            ],
            options={
                'verbose_name': 'Business Entity',
                'verbose_name_plural': 'Business Entities',
            },
        ),
    ]
