# Generated by Django 4.2.2 on 2023-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('vat_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT number')),
                ('iban', models.CharField(max_length=40, verbose_name='IBAN')),
                ('bic_swift', models.CharField(max_length=15, verbose_name='BIC/SWIFT')),
                ('registry_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('registry_code', models.CharField(max_length=20)),
                ('vat_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT number')),
                ('iban', models.CharField(max_length=40, verbose_name='IBAN')),
                ('bic_swift', models.CharField(max_length=15, verbose_name='BIC/SWIFT')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
