# Generated by Django 4.2.2 on 2023-06-24 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_invoice_lineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
