# Generated by Django 4.2.2 on 2023-06-28 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lineitem_amount_alter_lineitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 14, 23, 38, 574612, tzinfo=datetime.timezone.utc)),
        ),
    ]
