# Generated by Django 4.2.2 on 2023-06-28 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_invoice_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
